/*
 * MIT License
 *
 * Copyright (c) 2025 SiamDev by SiamDharmar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.siamdev.core.nostr

import rust.nostr.sdk.KindStandard as KindStd

actual enum class NostrKindStd(internal val native: KindStd) {
    METADATA(KindStd.METADATA),
    TEXT_NOTE(KindStd.TEXT_NOTE),
    CONTACT_LIST(KindStd.CONTACT_LIST),
    OPEN_TIMESTAMPS(KindStd.OPEN_TIMESTAMPS),
    EVENT_DELETION(KindStd.EVENT_DELETION),
    REPOST(KindStd.REPOST),
    GENERIC_REPOST(KindStd.GENERIC_REPOST),
    COMMENT(KindStd.COMMENT),
    REACTION(KindStd.REACTION),
    BADGE_AWARD(KindStd.BADGE_AWARD),
    BLOSSOM_AUTH(KindStd.BLOSSOM_AUTH),
    CHANNEL_CREATION(KindStd.CHANNEL_CREATION),
    CHANNEL_METADATA(KindStd.CHANNEL_METADATA),
    CHANNEL_MESSAGE(KindStd.CHANNEL_MESSAGE),
    CHANNEL_HIDE_MESSAGE(KindStd.CHANNEL_HIDE_MESSAGE),
    CHANNEL_MUTE_USER(KindStd.CHANNEL_MUTE_USER),
    GIT_PATCH(KindStd.GIT_PATCH),
    GIT_ISSUE(KindStd.GIT_ISSUE),
    GIT_REPLY(KindStd.GIT_REPLY),
    GIT_STATUS_OPEN(KindStd.GIT_STATUS_OPEN),
    GIT_STATUS_APPLIED(KindStd.GIT_STATUS_APPLIED),
    GIT_STATUS_CLOSED(KindStd.GIT_STATUS_CLOSED),
    GIT_STATUS_DRAFT(KindStd.GIT_STATUS_DRAFT),
    TORRENT(KindStd.TORRENT),
    TORRENT_COMMENT(KindStd.TORRENT_COMMENT),
    LABEL(KindStd.LABEL),
    WALLET_CONNECT_INFO(KindStd.WALLET_CONNECT_INFO),
    WALLET_CONNECT_NOTIFICATION(KindStd.WALLET_CONNECT_NOTIFICATION),
    REPORTING(KindStd.REPORTING),
    ZAP_PRIVATE_MESSAGE(KindStd.ZAP_PRIVATE_MESSAGE),
    ZAP_REQUEST(KindStd.ZAP_REQUEST),
    ZAP_RECEIPT(KindStd.ZAP_RECEIPT),
    MUTE_LIST(KindStd.MUTE_LIST),
    PIN_LIST(KindStd.PIN_LIST),
    BOOKMARKS(KindStd.BOOKMARKS),
    COMMUNITIES(KindStd.COMMUNITIES),
    PUBLIC_CHATS(KindStd.PUBLIC_CHATS),
    BLOCKED_RELAYS(KindStd.BLOCKED_RELAYS),
    SEARCH_RELAYS(KindStd.SEARCH_RELAYS),
    SIMPLE_GROUPS(KindStd.SIMPLE_GROUPS),
    INTERESTS(KindStd.INTERESTS),
    EMOJIS(KindStd.EMOJIS),
    FOLLOW_SET(KindStd.FOLLOW_SET),
    RELAY_SET(KindStd.RELAY_SET),
    BOOKMARK_SET(KindStd.BOOKMARK_SET),
    ARTICLES_CURATION_SET(KindStd.ARTICLES_CURATION_SET),
    VIDEOS_CURATION_SET(KindStd.VIDEOS_CURATION_SET),
    INTEREST_SET(KindStd.INTEREST_SET),
    EMOJI_SET(KindStd.EMOJI_SET),
    RELEASE_ARTIFACT_SET(KindStd.RELEASE_ARTIFACT_SET),
    RELAY_LIST(KindStd.RELAY_LIST),
    PEER_TO_PEER_ORDER(KindStd.PEER_TO_PEER_ORDER),
    REQUEST_TO_VANISH(KindStd.REQUEST_TO_VANISH),
    AUTHENTICATION(KindStd.AUTHENTICATION),
    WALLET_CONNECT_REQUEST(KindStd.WALLET_CONNECT_REQUEST),
    WALLET_CONNECT_RESPONSE(KindStd.WALLET_CONNECT_RESPONSE),
    NOSTR_CONNECT(KindStd.NOSTR_CONNECT),
    LIVE_EVENT(KindStd.LIVE_EVENT),
    LIVE_EVENT_MESSAGE(KindStd.LIVE_EVENT_MESSAGE),
    PROFILE_BADGES(KindStd.PROFILE_BADGES),
    BADGE_DEFINITION(KindStd.BADGE_DEFINITION),
    SEAL(KindStd.SEAL),
    GIFT_WRAP(KindStd.GIFT_WRAP),
    PRIVATE_DIRECT_MESSAGE(KindStd.PRIVATE_DIRECT_MESSAGE),
    INBOX_RELAYS(KindStd.INBOX_RELAYS),
    MLS_KEY_PACKAGE_RELAYS(KindStd.MLS_KEY_PACKAGE_RELAYS),
    MLS_KEY_PACKAGE(KindStd.MLS_KEY_PACKAGE),
    MLS_WELCOME(KindStd.MLS_WELCOME),
    MLS_GROUP_MESSAGE(KindStd.MLS_GROUP_MESSAGE),
    LONG_FORM_TEXT_NOTE(KindStd.LONG_FORM_TEXT_NOTE),
    GIT_REPO_ANNOUNCEMENT(KindStd.GIT_REPO_ANNOUNCEMENT),
    APPLICATION_SPECIFIC_DATA(KindStd.APPLICATION_SPECIFIC_DATA),
    FILE_METADATA(KindStd.FILE_METADATA),
    HTTP_AUTH(KindStd.HTTP_AUTH),
    SET_STALL(KindStd.SET_STALL),
    SET_PRODUCT(KindStd.SET_PRODUCT),
    JOB_FEEDBACK(KindStd.JOB_FEEDBACK),
    USER_STATUS(KindStd.USER_STATUS),
    CASHU_WALLET(KindStd.CASHU_WALLET),
    CASHU_WALLET_UNSPENT_PROOF(KindStd.CASHU_WALLET_UNSPENT_PROOF),
    CASHU_WALLET_SPENDING_HISTORY(KindStd.CASHU_WALLET_SPENDING_HISTORY),
    CODE_SNIPPET(KindStd.CODE_SNIPPET),
    POLL(KindStd.POLL),
    POLL_RESPONSE(KindStd.POLL_RESPONSE);
}
